image: alpine:latest

pages:
  script:
    - mkdir -p public
    - cp index-v2.html public/index.html
    - cp crm.html public/
    - cp -r img public/
  artifacts:
    paths:
      - public
  only:
    - main
